hhc/backend/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'backend'

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="Home"),
    path("whyChooseUs", views.whyChooseUs, name="WhyChooseUs"),
    path("aboutUs", views.aboutUs, name="AboutUs"),
    path("services", views.services, name="Services"),
    path("ourTeam", views.ourTeam, name="OurTeam"),
    path("ourGallery", views.ourGallery, name="OurGallery"),
    path("blogPosts", views.blogPosts, name="BlogPosts"),
    path("addBlogPosts/<int:blog_id>", views.addBlogPosts, name="AddBlogPosts"),
    path("contact", views.contact, name="Contact"),
    path("register", views.register, name="Register"),
    path("services/<int:service_id>", views.service, name="Service"),
    path("rate-us", views.rateUs, name="RateUs"),
    path("comment", views.comment, name="Comment"),
    
    #POST LOGIN
    path("login", views.login, name="Login"),
    
    path("error/404",views.error_404,name="Error404"),
]

hhc/hhc/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('frontend/',include('frontend.urls')),
    path('Home/',include('backend.urls', namespace='backend')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hhc/backend/models.py
from django.db import models

#CreatedBy UpdatedBy Helper
from django.contrib.auth import get_user_model
CustomUser = get_user_model()
import uuid

#Constant Import
from backend.constants import *

# Create your models here.
class Service(models.Model):
    id            = models.AutoField(primary_key=True)
    service_title = models.CharField(max_length=255)
    service_image = models.ImageField(upload_to='backend/services/images')
    service_description = models.TextField()
    support_image = models.ImageField(upload_to='backend/services/images/support_images')
    support_image2 = models.ImageField(upload_to='backend/services/images/support_images',default="")
    
    additional_content_title_1 = models.CharField(max_length=255,default="")
    additional_content_1       = models.TextField(default="")
    additional_content_title_2 = models.CharField(max_length=255,default="")
    additional_content_2       = models.TextField(default="")
    
    
    def __str__(self):
        return self.service_title
    
class Feedback(models.Model):
    id         = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name  = models.CharField(max_length=255, null=True, blank=True)
    email      = models.EmailField(null=True, blank=True)
    profile    = models.ImageField(upload_to='backend/feedback_and_comments/profiles', null=True, blank=True)
    rating     = models.IntegerField(null=True, blank=True)
    feedback   = models.TextField(null=True, blank=True)
    comment    = models.TextField(null=True, blank=True)
    blog_id    = models.IntegerField(null=True, blank=True, default=-1)
    type       = models.IntegerField(null=True, blank=True) #Type 1 => Feedback ; Type 2 => Comments
    status     = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        if self.type == FEEDBACK_TYPE_COMMENTS:
            type =  "Comment"
        elif self.type == FEEDBACK_TYPE_RATE_US:
            type = "Feedback"
        else:
            type = "Maid_Customer"
        return f"{self.first_name} {self.last_name} - {type}"

class TeamMember(models.Model):
    id               = models.AutoField(primary_key=True)
    profile          = models.ImageField(upload_to='backend/team_profiles/', blank=True, null=True)
    first_name       = models.CharField(max_length=50)
    last_name        = models.CharField(max_length=50)
    post             = models.CharField(max_length=50)
    facebook_profile = models.URLField(max_length=500, blank=True, null=True)
    twitter_profile  = models.URLField(max_length=500, blank=True, null=True)
    linkedin_profile = models.URLField(max_length=500, blank=True, null=True)
    
    level            = models.IntegerField(null=True, blank=True,default=0)
    
    created_at       = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at       = models.DateTimeField(auto_now=True, null=True, blank=True)
    
    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.post}"
    
 
class Blog(models.Model):
    id                 = models.AutoField(primary_key=True)
    blog_title         = models.CharField(max_length=255)
    blog_image         = models.ImageField(upload_to='backend/blogs/images')
    blog_description_1 = models.TextField()
    blog_description_2 = models.TextField()
    uploaded_by        = models.CharField(max_length=50)
    created_at         = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at         = models.DateTimeField(auto_now=True, null=True, blank=True)
    
    def __str__(self):
        return f"{self.blog_title} by {self.uploaded_by}"
    
class CustomeUser(models.Model):
    id          = models.AutoField(primary_key=True)
    uuid        = models.UUIDField(default=uuid.uuid4, editable=False)
    user_name   = models.CharField(max_length = 50)
    first_name  = models.CharField(max_length = 50)
    last_name   = models.CharField(max_length = 50)
    phone_number= models.IntegerField(null=True)
    address     = models.CharField(max_length = 300,null=True)
    pin         = models.IntegerField(null=True)
    email       = models.EmailField(unique = True,null=True)
    password    = models.CharField(max_length = 100,null=True)
    reason      = models.IntegerField(null=True)
    profile     = models.ImageField(upload_to='backend/users/profiles', null=True, blank=True)
    status      = models.IntegerField(null=True)
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.user_name

hhc/backend/views.py
from django.shortcuts import render , redirect ,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.shortcuts import render
from django.views import View

#Models
from .models import *

#Constants
from backend.constants import *

#Form Imports
from django import forms
from django.contrib.auth import authenticate,login,logout

#Messages
from django.contrib import messages

#URL Imports
from django.urls import reverse

#REGEX Imports
import re

#Mail Imports
from django.core.mail import send_mail

# Create your views here.
def index(request):
    #Service Nav-Bar Dynamic
    services = Service.objects.all()
    #Feedback Sub-Page Section
    ratings = Feedback.objects.filter(type=FEEDBACK_TYPE_RATE_US, status=ACTIVE, rating__gt=3).order_by('-created_at')[:3]
    blogs = Blog.objects.all()
    params    = {'ratings':ratings, 'blogs':blogs, 'services':services}
    
    return render(request,'backend/index.html',params)

def whyChooseUs(request):
    #Service Nav-Bar Dynamic
    services = Service.objects.all()
    params    = {'services':services}
    
    return render(request,'backend/why-choose.html',params)

def aboutUs(request):
    #Service Nav-Bar Dynamic
    services = Service.objects.all()
    
    #Team Sub-Page Section
    teamMembers=TeamMember.objects.filter(level=TEAM_MEMBER_LEVEL_HIGH)[:3]
    params    = {'teamMembers':teamMembers, 'services':services}
    
    return render(request,'backend/about.html',params)

def services(request):
    #Service Nav-Bar Dynamic
    services = Service.objects.all()
    params    = {'services':services}
    
    return render(request,'backend/services.html',params)

def ourTeam(request):
    #Service Nav-Bar Dynamic
    services = Service.objects.all()
    
    #TeamMembers
    teamMembers=TeamMember.objects.filter(level=TEAM_MEMBER_LEVEL_HIGH)[:3]
    params    = {'teamMembers':teamMembers, 'services':services}
    
    return render(request,'backend/team.html',params)

def ourGallery(request):
    #Service Nav-Bar Dynamic
    services = Service.objects.all()
    params    = {'services':services}
    
    return render(request,'backend/gallery.html',params)

def blogPosts(request):
    #Service Nav-Bar Dynamic
    services = Service.objects.all()
    
    #Blogs
    blogs = Blog.objects.all()
    params = {'blogs':blogs, 'services':services}
    
    return render(request,'backend/news.html',params)

def addBlogPosts(request,blog_id):
    
    services = Service.objects.all()
    blogs    = Blog.objects.all()
    comments = Feedback.objects.filter(type=FEEDBACK_TYPE_COMMENTS, status=ACTIVE, blog_id=blog_id).order_by('-created_at')[:3]

    try:
        blog = get_object_or_404(Blog,id=blog_id)
        params = {'blog':blog,'services':services,'blogs':blogs, 'comments':comments}
        return render(request,'backend/news-single.html',params)
    except Http404:
        return redirect('backend:Error404')

def contact(request):
    #Service Nav-Bar Dynamic
    services = Service.objects.all()
    params    = {'services':services}
    
    return render(request,'backend/contact.html',params)

def register(request):
    if request.method == 'POST': 
        
        first_name         = request.POST.get('form_name')
        last_name          = request.POST.get('form_last_name')
        phone_number       = request.POST.get('form_phn')
        address            = request.POST.get('form_address')
        pin                = request.POST.get('form_pin')
        email              = request.POST.get('form_email')
        user_name          = request.POST.get('form_username')
        password           = request.POST.get('form_password')
        reason             = request.POST.get('reason')
        status             = ACTIVE
        profile            = request.FILES.get('profile_photo')
        
        if not phone_number.isdigit() or len(phone_number) != 10:
            messages.error(request, 'Invalid phone number. Please enter a 10-digit numeric phone number.')
            return redirect('backend:Home')

        
        if validate_email(email):
            email_body = f"""
                            Dear {first_name} {last_name},

                            Welcome to House Help Connect! We're excited to have you join our community and begin your journey towards finding reliable house help or securing rewarding job opportunities.

                            At House Help Connect, we understand the importance of convenience, trust, and quality in household services. Whether you're a homeowner seeking reliable house help or a job seeker looking for meaningful employment, our platform is here to simplify the process and ensure a seamless experience for all.

                            As a new member, you now have access to a wide range of features and services designed to meet your needs:

                            - Explore our extensive database of house help profiles, each carefully curated to provide detailed information about experience, services offered, availability, and more.
                            - Utilize our advanced search and filtering options to find the perfect match based on your specific preferences and requirements.
                            - Benefit from our secure and user-friendly platform, equipped with state-of-the-art security measures to safeguard your personal information and ensure a safe browsing experience.
                            - Stay updated with the latest news, tips, and insights on household management, employment trends, and more through our informative blog and newsletter.

                            We're committed to providing you with the best possible experience, and we're here to support you every step of the way. If you have any questions, feedback, or concerns, please don't hesitate to reach out to our dedicated customer support team. We're always here to help!

                            Thank you for choosing House Help Connect. We hope you enjoy our services and find exactly what you're looking for.

                            Best regards,
                            House Help Connect Team
                        """
            send_mail(
                'House Help Connect :- Successfully Registered!',
                 email_body,
                'househelpconnect23@gmail.com',
                [email,'ayushmorebb@gmail.com'],
                fail_silently=False,
            )
        else:
            messages.error(request, 'Invalid email address. Please enter a valid email address.')
            return redirect('backend:Home')

        
        custome_user_instance = CustomeUser(user_name=user_name,first_name=first_name,last_name=last_name,phone_number=phone_number,address=address,pin=pin,email=email,password=password,reason=reason,profile=profile,status=status)
        custome_user_instance.profile = profile
        custome_user_instance.save()
        
        messages.success(request, 'Registered Successfull !')
        return redirect('backend:Home')

def service(request,service_id):
    try:
        service = get_object_or_404(Service,id=service_id)
        params = {'service':service}
        return render(request,'backend/service-info.html',params)
    except Http404:
        return redirect('backend:Error404')

def rateUs(request):
    
    if request.method == 'POST':
        full_name = request.POST.get('name', '')
        split_name = full_name.split()

        first_name = split_name[0] if split_name else ''
        last_name  = ' '.join(split_name[1:]) if len(split_name) > 1 else ''
        email      = request.POST.get('email')
        profile    = request.FILES.get('profile_photo')
        feedback   = request.POST.get('feedback')
        rating     = request.POST.get('rating')
        type       = FEEDBACK_TYPE_RATE_US
        status     = ACTIVE
        feedback_instance = Feedback(
                                    first_name = first_name,
                                    last_name  = last_name,
                                    email      = email,
                                    profile    = profile,
                                    feedback   = feedback,
                                    rating     = rating,
                                    type       = type,
                                    status     = status
                                )
        feedback_instance.profile = profile
        feedback_instance.save()
        messages.info(request,"Thank You So Much For The Feedback!")
        return redirect("backend:Home")
    
    
    
    return render(request,'backend/feedback.html')
    
def comment(request):

    if request.method == 'POST': 
        full_name = request.POST.get('fname', '')
        split_name = full_name.split()

        first_name  = split_name[0] if split_name else ''
        last_name   = ' '.join(split_name[1:]) if len(split_name) > 1 else ''
        email       = request.POST.get('form_email')
        profile     = request.FILES.get('profile_photo')
        comment     = request.POST.get('message')
        blog_id     = request.POST.get('blog_id')
        type        = FEEDBACK_TYPE_COMMENTS
        status      = ACTIVE
        feedback_instance = Feedback(
                                    first_name = first_name,
                                    last_name  = last_name,
                                    email      = email,
                                    profile    = profile,
                                    comment    = comment,
                                    blog_id    = blog_id,
                                    type       = type,
                                    status     = status
                                )
        feedback_instance.profile = profile
        feedback_instance.save()
        messages.success(request, 'We Received Your Comment!')
        return redirect('backend:AddBlogPosts',blog_id)
        
    else:

hhc/backend/templates/layouts/how-it-works.html
<section class="working-steps-area">
    <div class="container">
        <div class="sec-title text-center">
            <h3 id="how-it-works">How It Works</h3>
            <div class="title">Follow 4 Easy Steps</div>
        </div>
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                <ul class="fix text-center">
                    <!--Start Single working steps Box-->
                    <li class="single-working-steps-box wow fadeInUp">
                        <div class="icon-holder">
                            <span class="flaticon-clock"></span>
                            <div class="count">
                                <h5>01</h5>
                            </div>
                        </div>
                        <div class="text-holder">
                            <h4><a href="#">Search and<br> Shortlist</a></h4>
                            <p>Discover and choose cleaning experts.</p>
                        </div>
                    </li>
                    <!--End Single working steps Box-->
                    <!--Start Single working steps Box-->
                    <li class="single-working-steps-box wow fadeInUp" data-wow-delay="300ms">
                        <div class="icon-holder">
                            <span class="flaticon-architect"></span>
                            <div class="count">
                                <h5>02</h5>
                            </div>
                        </div>
                        <div class="text-holder">
                            <h4><a href="#">Schedule Your<br> Meet</a></h4>
                            <p>Book a convenient meeting time.</p>
                        </div>
                    </li>
                    <!--End Single working steps Box-->
                    <!--Start Single working steps Box-->
                    <li class="single-working-steps-box wow fadeInUp" data-wow-delay="600ms">
                        <div class="icon-holder">
                            <span class="flaticon-handshake-1"></span>
                            <div class="count">
                                <h5>03</h5>
                            </div>
                        </div>
                        <div class="text-holder">
                            <h4><a href="#">Meet Your<br> Cleaning Expert</a></h4>
                            <p>Connect with your chosen professional.</p>
                        </div>
                    </li>
                    <!--End Single working steps Box-->
                    <!--Start Single working steps Box-->
                    <li class="single-working-steps-box wow fadeInUp" data-wow-delay="900ms">
                        <div class="icon-holder">
                            <span class="flaticon-cleaning-service"></span>
                            <div class="count">
                                <h5>04</h5>
                            </div>
                        </div>
                        <div class="text-holder">
                            <h4><a href="#"></a>Relax &amp; Get a Best<br> Cleaning Service</h4>
                            <p>Enjoy top-notch cleaning effortlessly.</p>
                        </div>
                    </li>
                    <!--End Single working steps Box-->
                  
                </ul>
            </div>
        </div>
    </div>
</section>

hhc/backend/templates/layouts/main-footer.html
{% load static %}

<footer class="footer-area">
    <div class="shape wow fadeInRight" data-wow-duration="3000ms"><img class="zoom-fade" src="{% static 'backend/images/footer/shape1.png' %}" alt=""></div>
    <div class="container">
        <div class="row">
            <!--Start single footer widget-->
            <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12">
                <div class="single-footer-widget marbtm50">
                    <div class="footer-logo">
                        <a href="{% url 'backend:Home' %}">
                            <img src="{% static 'backend/images/resources/logo.png'%}" alt="Awesome Logo">
                        </a>
                    </div>
                    <div class="company-info">
                        <div class="text-box">
                            <p>We are professional carpet cleaning experts in your town. Right carpet to fill a space can contribute to the overall character of your home or office space.</p>
                        </div>    
                    </div>
                </div>
            </div>
            <!--End single footer widget-->
            <!--Start single footer widget-->
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
                <div class="single-footer-widget marleft70 marbtm50">
                    <div class="title">
                        <h3>Explore</h3>
                    </div>
                    <ul class="explore-links">
                        <li><a href="{% url 'backend:AboutUs' %}">About</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="{% url 'backend:WhyChooseUs' %}">Why Choose Us</a></li>
                        <li><a href="#">Plans & Pricing</a></li>
                        <li><a href="#how-it-works">How They Works</a></li>
                    </ul>   
                </div>
            </div>
            <!--End single footer widget-->
            <!--Start single footer widget-->
            {% comment %} <div class="col-xl-2 col-lg-6 col-md-6 col-sm-12">
                <div class="single-footer-widget marleft30">
                    <div class="title">
                        <h3>Legal</h3>
                    </div>
                    <ul class="legal-links">
                        <li><a href="#">Join us</a></li>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">News</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Terms of Use</a></li>
                    </ul>  
                </div>
            </div> {% endcomment %}
            <!--End single footer widget-->
            <!--Start single footer widget-->
            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12">
                <div class="single-footer-widget marleft40 pdtop50">
                    <div class="title">
                        <h3>You have any Question?</h3>
                    </div>
                    <ul class="contact-info">
                        <li>
                            <span>Contact us</span>
                            <h3>9324843109</h3>
                        </li>
                        <li>
                            <span>Request a Free Quote</span>
                            <h3>Fill out Form</h3>
                        </li>
                        <li>
                            <div class="text">
                                <p>SJ Road, Lower Parel (West),<br> Mumbai 400013, INDIA</p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <!--End single footer widget-->
            
        </div>
    </div>
</footer>

hhc/backend/templates/layouts/main-header.html
{% load static %}

<style>
    .custom-input {
        width: 100%;
        padding: 12px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ddd;  /* Softer border color */
        box-sizing: border-box;
        border-radius: 8px;  /* Slightly rounder corners */
        transition: border-color 0.3s;
        font-size: 16px;
        color: #333;  /* Darker text color */
        background-color: #f5f5f5;  /* Lighter background color */
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;  /* New font */
    }

    /* Add focus styling */
    .custom-input:focus {
        border-color: #e3563d;  /* Accent color on focus */
        outline: none;
    }

    /* Style for placeholder text */
    .custom-input::placeholder {
        color: #888;  /* Softer color for placeholder text */
    }

    /* Style for a submit button (optional) */
    .custom-submit-button {
        background-color: #e3563d;
        color: #fff;
        padding: 12px;
        border: none;
        border-radius: 8px;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.3s;
        padding-left:50%;
        padding-right:50%;
    }

    .custom-submit-button:hover {
        color : #e3563d;
        background-color: white;
        border: 1px solid #e3563d;
        border-radius: 8px;
    }
</style>


<header class="main-header stricky">
    <div class="main-box">
        <div class="inner-container clearfix">
            <div class="logo-box">
                <a href="{% url "backend:Home" %}">
                    <img src="{% static 'backend/images/resources/logo.png' %}" alt="Awesome Logo">
                </a>
            </div>
            <div class="nav-outer clearfix">
                <nav class="main-menu clearfix">
                    <div class="navbar-header clearfix">   	
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse clearfix">
                        <ul class="navigation clearfix">
                            <li class="dropdown current"><a href="{% url "backend:Home" %}">Home</a>
                            </li>
                            <li class="dropdown current"><a href="{% url 'backend:AboutUs' %}">About</a>
                            </li>
                            <li class="dropdown"><a href="{% url 'backend:Services' %}">Services</a>
                                <ul>
                                    {% comment %} <li><a href="{% url 'backend:Service' service_id=1 %}">Cleaning</a></li>
                                    <li><a href="{% url 'backend:Service' service_id=2 %}">Cooking</a></li>
                                    <li><a href="{% url 'backend:Service' service_id=3 %}">Laundry &amp; Washing</a></li>
                                    <li><a href="{% url 'backend:Service' service_id=4 %}">Baby Sitting </a></li> {% endcomment %}
                                    {% for service in services %}
                                        <li><a href={% url 'backend:Service' service_id=service.id  %}>{{service.service_title}}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>
                            <li class="dropdown current"><a href="{% url 'backend:WhyChooseUs' %}">Why Choose Us</a>
                            </li>
                            <li class="dropdown"><a href="#">Pages</a>
                                <ul>
                                    <li><a href="{% url 'backend:OurTeam' %}">Our Team</a></li>
                                    <li><a href="{% url 'backend:OurGallery' %}">Our Gallery</a></li>
                                    <li><a href="{% url 'backend:RateUs' %}" target="blank">Rate Us</a></li>
                                    {% comment %} <li><a href="{% static 'backend/error.html' %}">404 Error</a></li> {% endcomment %}
                                </ul>
                            </li>
                            <li class="dropdown"><a href="{% url 'backend:BlogPosts' %}">Blog</a>
                                <ul>
                                    <li><a href="{% url 'backend:BlogPosts' %}">Latest News</a></li>
                                    <li><a href="{% url 'backend:AddBlogPosts' blog_id=1 %}">News Details</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'backend:Contact' %}">Contact</a></li>
                        </ul>
                    </div>
                </nav>      
            </div>
            <div class="header-right clearfix">
                <div class="opening-time">
                    <p><i class="fa fa-clock-o" aria-hidden="true"></i>9:00 am to 6:00 pm</p>
                </div>
                <div class="button">
                    <a class="btn-two" href="#" data-toggle="modal" data-target="#LoginModal"><span>Login</span></a>
                </div>
            </div>  
        </div>
    </div>
</header>

<!-- Modal Section-->
    <!--1. Login Modal    -->
    <div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="LoginModalLabel" aria-hidden="true" style="margin-top:10%;">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="LoginModalLabel" style="color:#e3563d;">Login</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form method="POST" action="{% url 'backend:Login' %}">
              {% csrf_token %}
              <div class="modal-body">
                <div class="row">
                  <div class="col-md-1 form-group"></div>
                  <div class="col-md-10 form-group">
                      <input type="text" class="custom-input" id="uname" name="uname" placeholder="User Name" required>
                  </div>
                  <div class="col-md-1 form-group"></div>
                </div>
                <div class="row">
                  <div class="col-md-1 form-group"></div>
                  <div class="form-group col-md-10">
                      <input type="password" class="custom-input" id="password" name="password" placeholder="Create Password" title="Create Password" required>
                  </div>
                  <div class="col-md-1 form-group"></div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-1 form-group">
                </div>
                <div class="col-md-6 form-group" style="margin-left:15px;">
                    <button type="submit" class="custom-submit-button" id="loginBTN">Login</button>
                </div>
                <div class="col-md-5 form-group"></div>
              </div>
              {% comment %} <div class="modal-footer">
                <button type="button" class="custom-submit-button" data-dismiss="modal" style="background-color:#a1a1a1;">Close</button>
                <button type="submit" class="custom-submit-button" id="loginBTN">Login</button>
              </div> {% endcomment %}
            </form>
          </div>
        </div>
      </div>