hhc/dashboard/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'dashboard'

urlpatterns = [
    #POST LOGIN
    path("<int:user_id>", views.index, name="Dashboard"),
    path("profile", views.profile, name="Profile"),
    path("advance", views.advance, name="Advance"),
    path("verification", views.verification, name="Verification"),
    path("find-match", views.findMatch, name="FindMatch"),
    path("view-profile/<int:user_id>",views.viewProfile,name="ViewProfile"),
    path("comment", views.comment, name="Comment"),
    path("explore-maids/",views.exploreMaids,name="ExploreMaids"),
    path("explore-customers/",views.exploreCustomers,name="ExploreCustomers"),
    
    
    path("",views.logOut,name="LogOut")
]

hhc/hhc/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('frontend/',include('frontend.urls')),
    path('Home/',include('backend.urls', namespace='backend')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hhc/dashboard/models.py
from django.db import models

# Create your models here.


class UserExtraDetail(models.Model):
    id         = models.AutoField(primary_key=True)
    user_id    = models.IntegerField(null=True)
    user_name  = models.CharField(max_length = 50)
    first_name = models.CharField(max_length = 50)
    last_name  = models.CharField(max_length = 50)
    
    gender         = models.IntegerField(null=True)
    birth_date     = models.DateField(null=True, blank=True)
    prefered_lang  = models.CharField(max_length = 50)
    
    service_type        = models.JSONField(default=list,null=True,blank=True)
    available_days      = models.JSONField(default=list,null=True,blank=True)
    working_hours       = models.IntegerField(null=True)
    working_hours_from  = models.TimeField(null=True)
    working_hours_to    = models.TimeField(null=True)
    years_of_experience = models.IntegerField(null=True)
    skill_description   = models.TextField(null=True)
    reference_contact   = models.CharField(max_length=20)
    previous_salary     = models.IntegerField(null=True)
    expected_salary     = models.IntegerField(null=True)
    
    adhar_card  = models.ImageField(upload_to='dashboard/users/documents/adhar', null=True, blank=True)
    voting_card = models.ImageField(upload_to='dashboard/users/documents/voting',null=True, blank=True)
    
    profile_build_level = models.IntegerField(default=0,null=True)
    is_verified         = models.BooleanField(default=False,null=True)
    user_type           = models.IntegerField(null=True)
    
    created_at     = models.DateTimeField(auto_now_add=True)
    updated_at     = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.user_name}_{self.id}"

hhc/dashboard/views.py
from django.shortcuts import render , redirect ,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.shortcuts import render
from django.views import View

#Models
from .models import *
from backend.models import CustomeUser,Feedback,Service,Blog
from django.db.models import Q

#Constants
from dashboard.constants import *
from backend.constants import  *

#Form Imports
from django import forms
from django.contrib.auth import authenticate,login,logout

#Messages
from django.contrib import messages

#URL Imports
from django.urls import reverse

#Date Time Imports
from datetime import time

#JSON Imports
import json

#Arithmetic Imports
import random

# Mail Imports
from django.core.mail import send_mail

# Session Imports
from django.contrib.sessions.models import Session

# Create your views here.
def index(request,user_id):
    request.session['user_id'] =  user_id  #set the session variable for the current logged in user
    try:
        user = CustomeUser.objects.get(id = user_id,)
    except CustomeUser.DoesNotExist:
        user = None
        
    try:
        userExtraDetail = UserExtraDetail.objects.get(user_id = user_id,)
        profile_build_level = userExtraDetail.profile_build_level
    except UserExtraDetail.DoesNotExist:
        profile_build_level = 0
    if user is not None:
        params = {'user':user,'profile_build_level':profile_build_level}
        # messages.success(request, 'Login Successfull!')
        return render(request,'dashboard/dashboard.html',params)
    else:
        return redirect("backend:Error404")
    
def profile(request):
    try:
        userExtraDetail = UserExtraDetail.objects.get(user_id = request.session.get('user_id'))
        profile_build_level = userExtraDetail.profile_build_level
    except UserExtraDetail.DoesNotExist:
        profile_build_level = 0
        
    if request.method == 'POST':
        user_id            = request.POST.get('user_id')
        user_type          = request.POST.get('user_type') 
        user_name          = request.POST.get('uname')
        first_name         = request.POST.get('fname')
        last_name          = request.POST.get('lname')
        phone_number       = request.POST.get('phone')
        address            = request.POST.get('address')
        email              = request.POST.get('email')
        gender             = request.POST.get('gender')
        birth_date         = request.POST.get('birth_date')
        language           = request.POST.get('language')
        profile_build_level= PROFILE_BUILD_LEVEL_BASIC
        
        
        customeUserInstance = CustomeUser.objects.get(id = user_id)
        customeUserInstance.first_name   = first_name
        customeUserInstance.last_name    = last_name
        customeUserInstance.email        = email
        customeUserInstance.phone_number = phone_number
        customeUserInstance.address      = address
        customeUserInstance.reason       = user_type
        customeUserInstance.save()
        
        user_exists = UserExtraDetail.objects.filter(user_id=user_id).exists()
        if user_exists:
            userExtraDetail =  UserExtraDetail.objects.get(user_id=user_id)
            userExtraDetail.user_name  = user_name
            userExtraDetail.first_name = first_name
            userExtraDetail.last_name  = last_name
            
            userExtraDetail.gender        = gender
            userExtraDetail.birth_date    = birth_date
            userExtraDetail.prefered_lang = language
            
            userExtraDetail.user_type     = user_type
            
            userExtraDetail.save()
            
            messages.success(request, 'Update Successfully !')
            
            return redirect('dashboard:Profile')
        else:
            userExtraDetailInstance = UserExtraDetail(
                user_id    = user_id,
                user_name  = user_name,
                first_name = first_name,
                last_name  = last_name,
                
                gender         = gender,
                birth_date     = birth_date,
                prefered_lang  = language,
                
                profile_build_level = profile_build_level,
                user_type           = user_type
            )
            userExtraDetailInstance.save()
            messages.success(request, 'Build Successfully ! Proceed with Advance Tab')
            return redirect('dashboard:Advance')
        
    user = CustomeUser.objects.get(id = request.session.get('user_id'))
    try:
        extraUser =  UserExtraDetail.objects.get(user_id = request.session.get('user_id'))
        extraUser.birth_date = extraUser.birth_date.strftime('%Y-%m-%d')
        params = {'user':user, 'profile_build_level':profile_build_level, 'extraUser':extraUser}
        return render(request,'dashboard/build-profile.html',params)
    except UserExtraDetail.DoesNotExist:
        extraUser = {'gender':False, 'prefered_lang':False, 'birth_date':False }
        params = {'user':user, 'profile_build_level':profile_build_level, 'extraUser':extraUser}
        return render(request,'dashboard/build-profile.html',params)

def advance(request):
    try:
        userExtraDetail = UserExtraDetail.objects.get(user_id = request.session.get('user_id'))
        profile_build_level = userExtraDetail.profile_build_level
    except UserExtraDetail.DoesNotExist:
        messages.error(request, 'Proceed with Profile Tab First')
        return redirect('dashboard:Dashboard',user_id = request.session.get('user_id'))
    
    if profile_build_level < PROFILE_BUILD_LEVEL_BASIC:
        messages.error(request, 'Complete Profile First')
        return redirect('dashboard:Dashboard',user_id = request.session.get('user_id'))
    
    if request.method == 'POST':
        if request.POST.get('from') == "" or request.POST.get('to') == "":
            messages.error(request, 'Fill From and To')
            return redirect('dashboard:Advance')
        
        service_type   = json.dumps(request.POST.getlist('service_chekcbox'))
        available_days = json.dumps(request.POST.getlist('chekcboxDay'))
        working_hours  = request.POST.get('working_hours')
        from_hour = int(request.POST.get('from'))
        from_ampm = request.POST.get('from_ampm')
        to_hour = int(request.POST.get('to'))
        to_ampm = request.POST.get('to_ampm')
        
        # Convert the working hours to 24-hour format
        if from_ampm == 'PM' and from_hour != 12:
            from_hour += 12  # Add 12 hours if PM
        elif from_ampm == 'AM' and from_hour == 12:
            from_hour = 0  # Special case for 12 AM

        if to_ampm == 'PM' and to_hour != 12:
            to_hour += 12  # Add 12 hours if PM
        elif to_ampm == 'AM' and to_hour == 12:
            to_hour = 0  # Special case for 12 AM

        # Construct time objects for working hours
        working_hours_from = time(hour=from_hour, minute=0)
        working_hours_to = time(hour=to_hour, minute=0)

        
        years_of_experience = request.POST.get('years_of_exp')
        skill_description   = request.POST.get('skill_desc')
        reference_contact   = request.POST.get('reference_contact')
        previous_salary     = request.POST.get('prev_salary')
        expected_salary     =request.POST.get('expected_salary')
        
        user_exists = UserExtraDetail.objects.filter(user_id=request.session.get('user_id')).exists()
        if user_exists:
            userExtraDetail =  UserExtraDetail.objects.get(user_id=request.session.get('user_id'))
            userExtraDetail.service_type        = service_type
            userExtraDetail.available_days      = available_days
            userExtraDetail.working_hours       = working_hours
            userExtraDetail.working_hours_from  = working_hours_from
            userExtraDetail.working_hours_to    = working_hours_to
            userExtraDetail.years_of_experience = years_of_experience
            userExtraDetail.skill_description   = skill_description
            userExtraDetail.reference_contact   = reference_contact
            userExtraDetail.previous_salary     = previous_salary
            userExtraDetail.expected_salary     = expected_salary
            userExtraDetail.profile_build_level = PROFILE_BUILD_LEVEL_ADVANCE
            userExtraDetail.save()
            
            messages.success(request, 'Build Successfully ! Proceed with Verification Tab')
            return redirect('dashboard:Verification')
        
        else:
            
            messages.error(request, 'Something went wrong! Proceed with  Registration again')
            return redirect('dashboard:Dashboard',user_id = request.session.get('user_id'))
    
    
    user        = CustomeUser.objects.get(id = request.session.get('user_id'))
    user_exists = UserExtraDetail.objects.filter(user_id=request.session.get('user_id')).exists()
    
    if user_exists:
        userExtraDetails = UserExtraDetail.objects.get(user_id =  request.session.get('user_id'))
    
    params = {'user_type':user.reason,'user':user, 'userExtraDetails':userExtraDetails, 'profile_build_level':profile_build_level}
    return render(request,'dashboard/advance-profile.html',params)

def verification(request):
    try:
        userExtraDetail = UserExtraDetail.objects.get(user_id = request.session.get('user_id'))
        profile_build_level = userExtraDetail.profile_build_level
    except UserExtraDetail.DoesNotExist:
        messages.error(request, 'Proceed with Profile Tab First')
        return redirect('dashboard:Dashboard',user_id = request.session.get('user_id'))

    if profile_build_level < PROFILE_BUILD_LEVEL_ADVANCE:
        messages.error(request, 'Complete Profile First')
        return redirect('dashboard:Dashboard',user_id = request.session.get('user_id'))
    
    if request.method == 'POST':

hhc/dashboard/templates/layouts/main-dashboard-footer.html
<div class="dashboard-footer-spacer"></div>
    <div class="small-footer margin-top-15">
        <div class="small-footer-copyrights">
            © 2019 <strong>HHC</strong>. All Rights Reserved.
        </div>
        <ul class="footer-social-links">
            <li>
                <a href="#" title="Facebook" data-tippy-placement="top">
                    <i class="icon-brand-facebook-f"></i>
                </a>
            </li>
            <li>
                <a href="#" title="Twitter" data-tippy-placement="top">
                    <i class="icon-brand-twitter"></i>
                </a>
            </li>
            <li>
                <a href="#" title="Google Plus" data-tippy-placement="top">
                    <i class="icon-brand-google-plus-g"></i>
                </a>
            </li>
            <li>
                <a href="#" title="LinkedIn" data-tippy-placement="top">
                    <i class="icon-brand-linkedin-in"></i>
                </a>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>

hhc/dashboard/templates/layouts/main-dashboard-header.html
<header id="header-container" class="fullwidth dashboard-header not-sticky">

	<!-- Header -->
	<div id="header">
		<div class="container">
			
			<!-- Left Side Content -->
			<div class="left-side">
				
				<!-- Logo -->
				<div id="logo">
					<a href="index-2.html"><img src="images/logo.png" alt=""></a>
				</div>

				<!-- Main Navigation -->
				<nav id="navigation">
					<ul id="responsive">

						<li><a href="{% url 'dashboard:Dashboard' user_id=user.id %}">Home</a>
						</li>

						<li><a href="#">For Customers & Maids</a>
							<ul class="dropdown-nav">
								<li><a href="#">Find Maid</a>
									<ul class="dropdown-nav">
										<li><a href="{% url 'dashboard:ExploreMaids' %}">Explore Maids</a></li>
										<li><a href="#">Connect</a></li>
									</ul>
								</li>
								<li><a href="#">Find Customer</a>
                                    <ul>
                                        <li><a href="{% url 'dashboard:ExploreCustomers' %}">Explore Customers</a></li>
                                        <li><a href="#">Connect</a></li>
                                    </ul>
                                </li>
							</ul>
						</li>

						<li><a href="#" class="current">Dashboard</a>
							<ul class="dropdown-nav">
								<li><a href="{% url 'dashboard:Dashboard' user_id=user.id %}">Dashboard</a></li>
								<li><a href="{% url 'dashboard:Profile' %}">Profile</a></li>
								<li><a href="{% url 'dashboard:Advance' %}">Advance</a></li>
								<li><a href="{% url 'dashboard:Verification' %}">Verification</a></li>
								<li><a href="dashboard-manage-jobs.html">Find Your Match</a>
									{% comment %} <ul class="dropdown-nav">
										<li><a href="dashboard-manage-jobs.html">Manage Jobs</a></li>
										<li><a href="dashboard-manage-candidates.html">Manage Candidates</a></li>
										<li><a href="dashboard-post-a-job.html">Post a Job</a></li>
									</ul> {% endcomment %}
								</li>
								<li><a href="dashboard-manage-tasks.html">Salary Prediction</a>
									{% comment %} <ul class="dropdown-nav">
										<li><a href="dashboard-manage-tasks.html">Manage Tasks</a></li>
										<li><a href="dashboard-manage-bidders.html">Manage Bidders</a></li>
										<li><a href="dashboard-my-active-bids.html">My Active Bids</a></li>
										<li><a href="dashboard-post-a-task.html">Post a Task</a></li>
									</ul> {% endcomment %}
								</li>
								<li><a href="dashboard-settings.html">Settings</a></li>
							</ul>
						</li>

						<li><a href="#">Pages</a>
							<ul class="dropdown-nav">
								<li><a href="pages-blog.html">Blog</a></li>
								<li><a href="pages-pricing-plans.html">Pricing</a></li>
								<li><a href="pages-contact.html">Contact</a></li>
							</ul>
						</li>

					</ul>
				</nav>
				<div class="clearfix"></div>
				<!-- Main Navigation / End -->
				
			</div>
			<!-- Left Side Content / End -->


			<!-- Right Side Content / End -->
			<div class="right-side">

				<!--  User Notifications -->
				{% comment %} <div class="header-widget hide-on-mobile">
					
					<!-- Notifications -->
					<div class="header-notifications">

						<!-- Trigger -->
						<div class="header-notifications-trigger">
							<a href="#"><i class="icon-feather-bell"></i><span>4</span></a>
						</div>

						<!-- Dropdown -->
						<div class="header-notifications-dropdown">

							<div class="header-notifications-headline">
								<h4>Notifications</h4>
								<button class="mark-as-read ripple-effect-dark" title="Mark all as read" data-tippy-placement="left">
									<i class="icon-feather-check-square"></i>
								</button>
							</div>

							<div class="header-notifications-content">
								<div class="header-notifications-scroll" data-simplebar>
									<ul>
										<!-- Notification -->
										<li class="notifications-not-read">
											<a href="dashboard-manage-candidates.html">
												<span class="notification-icon"><i class="icon-material-outline-group"></i></span>
												<span class="notification-text">
													<strong>Michael Shannah</strong> applied for a job <span class="color">Full Stack Software Engineer</span>
												</span>
											</a>
										</li>

										<!-- Notification -->
										<li>
											<a href="dashboard-manage-bidders.html">
												<span class="notification-icon"><i class=" icon-material-outline-gavel"></i></span>
												<span class="notification-text">
													<strong>Gilbert Allanis</strong> placed a bid on your <span class="color">iOS App Development</span> project
												</span>
											</a>
										</li>

										<!-- Notification -->
										<li>
											<a href="dashboard-manage-jobs.html">
												<span class="notification-icon"><i class="icon-material-outline-autorenew"></i></span>
												<span class="notification-text">
													Your job listing <span class="color">Full Stack PHP Developer</span> is expiring.
												</span>
											</a>
										</li>

										<!-- Notification -->
										<li>
											<a href="dashboard-manage-candidates.html">
												<span class="notification-icon"><i class="icon-material-outline-group"></i></span>
												<span class="notification-text">
													<strong>Sindy Forrest</strong> applied for a job <span class="color">Full Stack Software Engineer</span>
												</span>
											</a>
										</li>
									</ul>
								</div>
							</div>

						</div>

					</div>
					
					<!-- Messages -->
					<div class="header-notifications">
						<div class="header-notifications-trigger">
							<a href="#"><i class="icon-feather-mail"></i><span>3</span></a>
						</div>

						<!-- Dropdown -->
						<div class="header-notifications-dropdown">

							<div class="header-notifications-headline">
								<h4>Messages</h4>
								<button class="mark-as-read ripple-effect-dark" title="Mark all as read" data-tippy-placement="left">
									<i class="icon-feather-check-square"></i>
								</button>
							</div>

							<div class="header-notifications-content">
								<div class="header-notifications-scroll" data-simplebar>
									<ul>
										<!-- Notification -->
										<li class="notifications-not-read">
											<a href="dashboard-messages.html">
												<span class="notification-avatar status-online"><img src="images/user-avatar-small-03.jpg" alt=""></span>
												<div class="notification-text">
													<strong>David Peterson</strong>
													<p class="notification-msg-text">Thanks for reaching out. I'm quite busy right now on many...</p>
													<span class="color">4 hours ago</span>
												</div>
											</a>
										</li>

										<!-- Notification -->
										<li class="notifications-not-read">
											<a href="dashboard-messages.html">
												<span class="notification-avatar status-offline"><img src="images/user-avatar-small-02.jpg" alt=""></span>
												<div class="notification-text">
													<strong>Sindy Forest</strong>
													<p class="notification-msg-text">Hi Tom! Hate to break it to you, but I'm actually on vacation until...</p>
													<span class="color">Yesterday</span>
												</div>
											</a>
										</li>

										<!-- Notification -->
										<li class="notifications-not-read">
											<a href="dashboard-messages.html">
												<span class="notification-avatar status-online"><img src="images/user-avatar-placeholder.png" alt=""></span>
												<div class="notification-text">
													<strong>Marcin Kowalski</strong>
													<p class="notification-msg-text">I received payment. Thanks for cooperation!</p>
													<span class="color">Yesterday</span>
												</div>
											</a>
										</li>
									</ul>
								</div>
							</div>

							<a href="dashboard-messages.html" class="header-notifications-button ripple-effect button-sliding-icon">View All Messages<i class="icon-material-outline-arrow-right-alt"></i></a>
						</div>
					</div>

				</div> {% endcomment %}
				<!--  User Notifications / End -->

				<!-- User Menu -->
				<div class="header-widget">

					<!-- Messages -->
					<div class="header-notifications user-menu">
						<div class="header-notifications-trigger">
							<a href="#"><div class="user-avatar status-online"><img src="/media/{{user.profile}}" alt="" style="width: 100%; height: 50px; object-fit: cover;"></div></a>
						</div>

						<!-- Dropdown -->
						<div class="header-notifications-dropdown">

							<!-- User Status -->
							<div class="user-status">

								<!-- User Name / Avatar -->
								<div class="user-details">
									<div class="user-avatar status-online"><img src="/media/{{user.profile}}" alt="" style="width: 100%; height: 200px; object-fit: cover;"></div>
									<div class="user-name">
										Tom Smith <span>Freelancer</span>
									</div>
								</div>
								
								<!-- User Status Switcher -->
								<div class="status-switch" id="snackbar-user-status">
									<label class="user-online current-status">Online</label>
									<label class="user-invisible">Invisible</label>
									<!-- Status Indicator -->
									<span class="status-indicator" aria-hidden="true"></span>
								</div>	
						</div>
						
						<ul class="user-menu-small-nav">
							<li><a href="dashboard.html"><i class="icon-material-outline-dashboard"></i> Dashboard</a></li>
							<li><a href="dashboard-settings.html"><i class="icon-material-outline-settings"></i> Settings</a></li>
							<li><a href="index-logged-out.html"><i class="icon-material-outline-power-settings-new"></i> Logout</a></li>
						</ul>

						</div>
					</div>

				</div>
				<!-- User Menu / End -->

				<!-- Mobile Navigation Button -->
				<span class="mmenu-trigger">
					<button class="hamburger hamburger--collapse" type="button">
						<span class="hamburger-box">
							<span class="hamburger-inner"></span>
						</span>
					</button>
				</span>

			</div>
			<!-- Right Side Content / End -->

		</div>
	</div>
	<!-- Header / End -->

</header>

hhc/dashboard/templates/layouts/main-dashboard-sidebar.html
<div class="dashboard-sidebar">
    <div class="dashboard-sidebar-inner" data-simplebar>
        <div class="dashboard-nav-container">

            <!-- Responsive Navigation Trigger -->
            <a href="#" class="dashboard-responsive-nav-trigger">
                <span class="hamburger hamburger--collapse" >
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </span>
                <span class="trigger-title">Dashboard Navigation</span>
            </a>
            
            <!-- Navigation -->
            <div class="dashboard-nav">
                <div class="dashboard-nav-inner">
                    <ul data-submenu-title="Start">
                        <li class="{% if request.resolver_match.url_name == 'Dashboard' and request.resolver_match.kwargs.user_id == user.id %}active{% endif %}"><a href="{% url 'dashboard:Dashboard' user_id=user.id %}"><i class="icon-material-outline-dashboard"></i> Dashboard </a></li>
                        <li class="{% if request.resolver_match.url_name == 'Profile'%}active{% endif %}"><a href="{% url 'dashboard:Profile' %}"><i class="icon-material-outline-account-circle"></i> Profile </a></li>
                        <li class="{% if request.resolver_match.url_name == 'Advance'%}active{% endif %}"><a href="{% url 'dashboard:Advance' %}"><i class="icon-material-outline-star-border"></i> Advance {% if profile_build_level < 1  %}  <i class="icon-line-awesome-lock"></i>{% endif %}</a></li>
                        <li class="{% if request.resolver_match.url_name == 'Verification'%}active{% endif %}"><a href="{% url 'dashboard:Verification' %}"><i class="icon-material-outline-search"></i> Verification {% if profile_build_level < 2  %} <i class="icon-line-awesome-lock"></i> {% endif %}</a></li>
                    </ul>
                    
                    <ul data-submenu-title="Advance Features">
                        <li class="{% if request.resolver_match.url_name == 'FindMatch'%}active{% endif %}"><a href="{% url 'dashboard:FindMatch' %}"><i class="icon-line-awesome-heart"></i>Find Your Match {% if profile_build_level < 3  %} <i class="icon-line-awesome-lock"></i> {% endif %}</a></li>
                        <li><a href="#"><i class="icon-line-awesome-money"></i>Salary Prediction {% if profile_build_level < 3  %} <i class="icon-line-awesome-lock"></i> {% endif %}</a></li>
                    </ul>

                    <ul data-submenu-title="Account">
                        <li><a href="dashboard-settings.html"><i class="icon-material-outline-settings"></i> Settings</a></li>
                        <li><a href="{% url 'dashboard:LogOut' %}"><i class="icon-material-outline-power-settings-new"></i> Logout</a></li>
                    </ul>
                    
                </div>
            </div>
            <!-- Navigation / End -->

        </div>
    </div>
</div>